"use client"

// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/update-barrels.mjs
// Barrel for src/components/TablePage/ModalProvider — exports all .ts/.tsx (excluding tests, stories, .d.ts)

export * from "./ModalContext";
export * from "./ModalProvider";
