// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/update-barrels.mjs
// Barrel for src/components/shared — exports all .ts/.tsx (excluding tests, stories, .d.ts)

export * from "./AutoResizingTextarea";
export * from "./Modal";
export * from "./TagComponents";
