
export const getRandomTitle = () => {
    const randomPrefix = titlePrefixes[Math.random() * titlePrefixes.length | 0];
    const randomMiddle = tileMiddle[Math.random() * tileMiddle.length | 0];
    const randomSuffix = titleSuffixes[Math.random() * titleSuffixes.length | 0];
    return `${randomPrefix} ${randomMiddle} ${randomSuffix}`;
}

export const getRandomTagline = () => taglines[Math.random() * taglines.length | 0];


const titlePrefixes = [
    "The Knights of The",
    "The Fellowship of The",
    "The Order of The",
    "The Infamous",
    "The Legendary",
    "The Dubious",
    "The Sworn Guardians of The",
    "The Ancient Guild of The",
    "The Unstoppable",
    "The Misfit",
    "The Chaotic",
    "The Brave",
    "The Forgotten",
    "The Wandering",
    "The Noble Council of The",
    "The Dread Pirates of The",
    "The Honorable Society of The",
    "The Cursed",
    "The Unlikely Heroes of The",
    "The Elders of The",
    "The Seekers of The",
    "The Champions of The",
    "The Heralds of The",
    "The Disciples of The",
    "The Ragtag Band of The",
    "The Cult of The",
];

const tileMiddle = [
    "Round",
    "Kitchen",
    "Deepest",
    "Sorcery",
    "Munchkin",
    "Shenanigan",
    "Secret",
    "Dungeon",
    "Fireside",
    "Tabletop",
    "Midnight",
    "Tavern",
    "Goblin",
    "Dragon",
    "Critical",
    "Natural Twenty",
    "Counterspell",
    "Nat One",
    "Cardboard",
    "Dice Tower",
    "Campaign",
    "Lore",
    "Awkward",
    "Unhinged",
    "Chaotic Neutral",
    "Homebrew",
    "Side Quest",
];

const titleSuffixes = [
    "Table",
    "Dungeon",
    "Cave",
    "Crew",
    "Team",
    "League",
    "Horde",
    "Party",
    "Conclave",
    "Collective",
    "Alliance",
    "Syndicate",
    "Guild",
    "Cabal",
    "Council",
    "Expedition",
    "Enclave",
    "Consortium",
    "Troupe",
    "Vanguard",
    "Cohort",
    "Brotherhood",
    "Sisterhood",
    "Pantheon",
    "Assembly",
    "Coven",
];

const taglines = [
    "Everyone is welcome!",
    "Looking for serious players.",
    "Get in nerds, we're gaming!",
    "If you aren't there, you're square.",
    "It will be legendary!",
    "Beginners welcome — we were all level 1 once.",
    "No experience necessary. Snacks encouraged.",
    "Roleplayers, board gamers, and chaos gremlins welcome.",
    "We don't metagame. Much.",
    "All alignments accepted. True Neutral gets the snacks.",
    "Where every session is a one-shot... until it isn't.",
    "Homebrew rules may apply.",
    "Warning: may contain excessive lore.",
    "Critical failures celebrated as much as critical hits.",
    "No powergamers. Okay, maybe one powergamer.",
    "We finish campaigns. (Eventually.)",
    "Veteran players seeking worthy companions.",
    "Casuals only — we're here for the vibes.",
    "Serious about fun, not about rules.",
    "Min-maxers need not apply.",
    "For those who read the rulebook... and those who definitely didn't.",
    "Roll for initiative. Arrive on time.",
    "Side quests are the main quest here.",
    "Chaotic good energy required.",
    "If you bring snacks, you can name the first NPC.",
    "We read the rulebook so you don't have to.",
    "Wargamers only — no take-backs, no mercy.",
    "Everyone welcome. Meeple provided.",
    "We always play the longest game on the shelf.",
    "Worker placement. Resource management. Existential dread.",
    "No phones at the table! We're here for the game.",
    "Someone always flips the table. Metaphorically. Usually.",
    "We have a designated rules lawyer. It's fine.",
    "Cooperative games only — we can't handle another Monopoly incident.",
    "Teaching time is half the fun!",
];
