#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const cwd = process.cwd();
const SRC_DIR = path.join(cwd, "src");
const DIST_DIR = "dist";

function toPosix(p) {
    return p.split(path.sep).join("/");
}

function exists(p) {
    return fs.existsSync(p);
}

function read(filePath) {
    return fs.readFileSync(filePath, "utf8");
}

function writeIfChanged(filePath, content) {
    const current = exists(filePath) ? read(filePath) : null;
    if (current === content) return false;
    fs.writeFileSync(filePath, content, "utf8");
    return true;
}

function isTsLike(fileName) {
    return /\.(ts|tsx)$/i.test(fileName) && !fileName.endsWith(".d.ts");
}

function shouldSkipFile(fileName) {
    return (
        fileName.startsWith(".") ||
        fileName.endsWith(".d.ts") ||
        /\.(test|spec|stories)\.(ts|tsx)$/i.test(fileName)
    );
}

function stripBom(text) {
    return text?.charCodeAt(0) === 0xfeff ? text.slice(1) : text;
}

function hasUseClientDirective(text) {
    if (!text) return false;
    text = stripBom(text);
    const stripped = text.replace(/^\s*(\/\/.*\n|\/\*[\s\S]*?\*\/\s*)*/g, "");
    return /^["']use client["']\s*;?/.test(stripped);
}

function hasDefaultExport(text) {
    return /^\s*export\s+default\s+/m.test(text || "");
}

function listDirs(rootDir) {
    const out = [];

    function walk(dir) {
        out.push(dir);
        for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
            if (!entry.isDirectory()) continue;
            if (entry.name === "node_modules" || entry.name.startsWith(".")) continue;
            walk(path.join(dir, entry.name));
        }
    }

    if (exists(rootDir)) {
        walk(rootDir);
    }

    return out;
}

function listImmediateDirs(rootDir) {
    if (!exists(rootDir)) return [];
    return fs
        .readdirSync(rootDir, { withFileTypes: true })
        .filter((d) => d.isDirectory() && !d.name.startsWith("."))
        .map((d) => d.name)
        .sort();
}

function collectModulesForBarrel(dir) {
    const out = new Map();

    function walk(currentDir) {
        for (const entry of fs.readdirSync(currentDir, { withFileTypes: true })) {
            const full = path.join(currentDir, entry.name);

            if (entry.isDirectory()) {
                if (entry.name === "node_modules" || entry.name.startsWith(".")) continue;
                walk(full);
                continue;
            }

            if (!entry.isFile()) continue;
            if (!isTsLike(entry.name) || shouldSkipFile(entry.name)) continue;

            let relNoExt = toPosix(path.relative(dir, full)).replace(/\.(ts|tsx)$/i, "");

            if (relNoExt === "index") continue;
            if (relNoExt.endsWith("/index")) {
                relNoExt = relNoExt.slice(0, -"/index".length);
            }

            const ext = path.extname(entry.name);
            const base = path.basename(entry.name, ext);
            const text = read(full);

            const rec = {
                rel: relNoExt,
                base,
                ext,
                isClient: hasUseClientDirective(text),
                isDefault: hasDefaultExport(text),
            };

            const existing = out.get(relNoExt);
            if (!existing || (existing.ext === ".ts" && rec.ext === ".tsx")) {
                out.set(relNoExt, rec);
            }
        }
    }

    walk(dir);
    return [...out.values()].sort((a, b) => a.rel.localeCompare(b.rel));
}

function generateInternalBarrel(modules) {
    const hasClient = modules.some((m) => m.isClient);
    const lines = [];

    if (hasClient) {
        lines.push('"use client";', "");
    }

    lines.push("// AUTO-GENERATED FILE. DO NOT EDIT.");
    lines.push("// Generated by scripts/update-barrels.mjs");
    lines.push("");

    for (const mod of modules) {
        lines.push(`export * from "./${mod.rel}";`);
        if (mod.isDefault && mod.base !== "index") {
            lines.push(`export { default as ${mod.base} } from "./${mod.rel}";`);
        }
    }

    lines.push("");
    return lines.join("\n");
}

function cleanGeneratedIndexes(rootDir) {
    let removed = 0;

    for (const dir of listDirs(rootDir)) {
        const indexTs = path.join(dir, "index.ts");
        const indexTsx = path.join(dir, "index.tsx");

        if (exists(indexTsx)) continue;
        if (!exists(indexTs)) continue;

        const text = read(indexTs);
        if (text.startsWith("// AUTO-GENERATED FILE. DO NOT EDIT.")) {
            fs.unlinkSync(indexTs);
            removed++;
        }
    }

    return removed;
}

function writeInternalBarrels(rootDir) {
    const dirs = listDirs(rootDir).sort(
        (a, b) => b.split(path.sep).length - a.split(path.sep).length
    );

    let wrote = false;

    for (const dir of dirs) {
        const handwrittenTsxIndex = path.join(dir, "index.tsx");
        if (exists(handwrittenTsxIndex)) continue;

        const modules = collectModulesForBarrel(dir);
        const outPath = path.join(dir, "index.ts");

        if (modules.length === 0) {
            if (exists(outPath)) {
                const text = read(outPath);
                if (text.startsWith("// AUTO-GENERATED FILE. DO NOT EDIT.")) {
                    fs.unlinkSync(outPath);
                }
            }
            continue;
        }

        const content = generateInternalBarrel(modules);
        if (writeIfChanged(outPath, content)) {
            wrote = true;
            console.log(`[barrels] wrote ${toPosix(path.relative(cwd, outPath))}`);
        }
    }

    return wrote;
}

function generatePublicEntryFile(target) {
    return [
        "// AUTO-GENERATED FILE. DO NOT EDIT.",
        "// Generated by scripts/update-barrels.mjs",
        "",
        `export * from "${target}";`,
        "",
    ].join("\n");
}

function writePublicEntries() {
    const componentsDir = path.join(SRC_DIR, "components");
    const mocksDir = path.join(SRC_DIR, "mocks");
    const typesDir = path.join(SRC_DIR, "types");

    let wrote = false;
    const publicNames = [];

    for (const name of listImmediateDirs(componentsDir)) {
        const outFile = path.join(SRC_DIR, `${name}.ts`);
        const content = generatePublicEntryFile(`./components/${name}`);
        if (writeIfChanged(outFile, content)) {
            wrote = true;
            console.log(`[barrels] wrote ${toPosix(path.relative(cwd, outFile))}`);
        }
        publicNames.push(name);
    }

    if (exists(mocksDir)) {
        publicNames.push("mocks");
    }

    if (exists(typesDir)) {
        publicNames.push("types");
        const outFile = path.join(SRC_DIR, "types.ts");
        const content = generatePublicEntryFile(`./types`);
        if (writeIfChanged(outFile, content)) {
            wrote = true;
            console.log(`[barrels] wrote ${toPosix(path.relative(cwd, outFile))}`);
        }
    }

    const indexFile = path.join(SRC_DIR, "index.ts");
    const indexContent = [
        "// AUTO-GENERATED FILE. DO NOT EDIT.",
        "// Generated by scripts/update-barrels.mjs",
        "",
        ...publicNames
            .filter((name) => name !== "mocks")
            .map((name) => `export * from "./${name}";`),
        "",
    ].join("\n");

    if (writeIfChanged(indexFile, indexContent)) {
        wrote = true;
        console.log(`[barrels] wrote ${toPosix(path.relative(cwd, indexFile))}`);
    }

    return { wrote, publicNames };
}

function buildExportTarget(name) {
    return {
        types: `./${DIST_DIR}/${name}.d.ts`,
        import: `./${DIST_DIR}/${name}.mjs`,
        require: `./${DIST_DIR}/${name}.cjs`,
        default: `./${DIST_DIR}/${name}.mjs`,
    };
}

function updatePackageJson(publicNames) {
    const pkgPath = path.join(cwd, "package.json");
    if (!exists(pkgPath)) {
        console.warn("[barrels] package.json not found, skipping exports update");
        return false;
    }

    const pkg = JSON.parse(read(pkgPath));
    const existingExports = pkg.exports && typeof pkg.exports === "object" ? pkg.exports : {};

    const managedKeys = new Set([".", ...publicNames.map((name) => `./${name}`)]);

    const nextExports = {};

    // preserve unmanaged export keys
    for (const [key, value] of Object.entries(existingExports)) {
        if (!managedKeys.has(key)) {
            nextExports[key] = value;
        }
    }

    // managed root export
    nextExports["."] = buildExportTarget("index");

    // managed subpath exports
    for (const name of publicNames) {
        nextExports[`./${name}`] = buildExportTarget(name);
    }

    // stable ordering
    const orderedExports = {};
    for (const key of Object.keys(nextExports).sort((a, b) => {
        if (a === ".") return -1;
        if (b === ".") return 1;
        return a.localeCompare(b);
    })) {
        orderedExports[key] = nextExports[key];
    }

    pkg.exports = orderedExports;

    // nice defaults if not already present
    if (!pkg.types) {
        pkg.types = `./${DIST_DIR}/index.d.ts`;
    }

    const nextText = JSON.stringify(pkg, null, 2) + "\n";
    const changed = writeIfChanged(pkgPath, nextText);

    if (changed) {
        console.log("[barrels] updated package.json exports");
    }

    return changed;
}

function main() {
    const componentsRoot = path.join(SRC_DIR, "components");
    const mocksRoot = path.join(SRC_DIR, "mocks");
    const typesRoot = path.join(SRC_DIR, "types");

    cleanGeneratedIndexes(componentsRoot);
    cleanGeneratedIndexes(mocksRoot);
    cleanGeneratedIndexes(typesRoot);

    writeInternalBarrels(componentsRoot);
    writeInternalBarrels(mocksRoot);
    writeInternalBarrels(typesRoot);

    const { publicNames } = writePublicEntries();
    updatePackageJson(publicNames);
}

try {
    main();
} catch (err) {
    console.error("[barrels] failed:", err?.stack || err?.message || err);
    process.exit(1);
}